security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login
 
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:       true
            anonymous:    true
 
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
 
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }


















#security:
#    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    providers:
#        fos_userbundle:
#            id: fos_user.user_provider.username
#        my_custom_hwi_provider:
#             id: app_user.oauth_user_provider
#
#    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                default_target_path: /
#                login_path: /login
#                check_path: /login_check
#            oauth:
#                resource_owners:
#                    facebook:           "/login/check-facebook"
#                login_path:        /login
#                failure_path:      /login
# 
#                oauth_user_provider:
#                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
#                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
#                    service: my_user_provider
#            logout:       true
#            anonymous:    true
#        login:
#            pattern:  ^/login$
#            security: false
# 
#            remember_me:
#                key: "%secret%"
#                lifetime: 31536000 # 365 days in seconds
#                path: /
#                domain: ~ # Defaults to the current domain from $_SERVER
#
#    access_control:
#        - { path: ^/furniture, role: ROLE_USER }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, role: ROLE_USER }
